/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreativePartnerRouteImport } from './routes/creative-partner'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VisionTokenRouteImport } from './routes/vision.$token'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as SupplierTokenRouteImport } from './routes/supplier.$token'
import { Route as PlannerTokenRouteImport } from './routes/planner.$token'
import { Route as LicenseTokenRouteImport } from './routes/license.$token'
import { Route as HelpTaxRouteImport } from './routes/help.tax'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as BriefTokenRouteImport } from './routes/brief.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as ApiAssistantStreamRouteImport } from './routes/api/assistant/stream'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicCronFetchDailyTrendsRouteImport } from './routes/api/public/cron/fetch-daily-trends'
import { Route as ApiPublicCronDeadlineRemindersRouteImport } from './routes/api/public/cron/deadline-reminders'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativePartnerRoute = CreativePartnerRouteImport.update({
  id: '/creative-partner',
  path: '/creative-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionTokenRoute = VisionTokenRouteImport.update({
  id: '/vision/$token',
  path: '/vision/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTokenRoute = SupplierTokenRouteImport.update({
  id: '/supplier/$token',
  path: '/supplier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerTokenRoute = PlannerTokenRouteImport.update({
  id: '/planner/$token',
  path: '/planner/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseTokenRoute = LicenseTokenRouteImport.update({
  id: '/license/$token',
  path: '/license/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpTaxRoute = HelpTaxRouteImport.update({
  id: '/help/tax',
  path: '/help/tax',
  getParentRoute: () => rootRouteImport,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefTokenRoute = BriefTokenRouteImport.update({
  id: '/brief/$token',
  path: '/brief/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantStreamRoute = ApiAssistantStreamRouteImport.update({
  id: '/api/assistant/stream',
  path: '/api/assistant/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFetchDailyTrendsRoute =
  ApiPublicCronFetchDailyTrendsRouteImport.update({
    id: '/api/public/cron/fetch-daily-trends',
    path: '/api/public/cron/fetch-daily-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDeadlineRemindersRoute =
  ApiPublicCronDeadlineRemindersRouteImport.update({
    id: '/api/public/cron/deadline-reminders',
    path: '/api/public/cron/deadline-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/creative-partner': typeof CreativePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/labs': typeof LabsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brief/$token': typeof BriefTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/tax': typeof HelpTaxRoute
  '/license/$token': typeof LicenseTokenRoute
  '/planner/$token': typeof PlannerTokenRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/vision/$token': typeof VisionTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/api/assistant/stream': typeof ApiAssistantStreamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/deadline-reminders': typeof ApiPublicCronDeadlineRemindersRoute
  '/api/public/cron/fetch-daily-trends': typeof ApiPublicCronFetchDailyTrendsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/creative-partner': typeof CreativePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/labs': typeof LabsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brief/$token': typeof BriefTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/tax': typeof HelpTaxRoute
  '/license/$token': typeof LicenseTokenRoute
  '/planner/$token': typeof PlannerTokenRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/vision/$token': typeof VisionTokenRoute
  '/blog': typeof BlogIndexRoute
  '/api/assistant/stream': typeof ApiAssistantStreamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/deadline-reminders': typeof ApiPublicCronDeadlineRemindersRoute
  '/api/public/cron/fetch-daily-trends': typeof ApiPublicCronFetchDailyTrendsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/creative-partner': typeof CreativePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/labs': typeof LabsRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brief/$token': typeof BriefTokenRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/tax': typeof HelpTaxRoute
  '/license/$token': typeof LicenseTokenRoute
  '/planner/$token': typeof PlannerTokenRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/track/$token': typeof TrackTokenRoute
  '/vision/$token': typeof VisionTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/api/assistant/stream': typeof ApiAssistantStreamRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/api/public/cron/deadline-reminders': typeof ApiPublicCronDeadlineRemindersRoute
  '/api/public/cron/fetch-daily-trends': typeof ApiPublicCronFetchDailyTrendsRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/cookies'
    | '/creative-partner'
    | '/dashboard'
    | '/labs'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/survey'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/auth/forgot'
    | '/blog/$slug'
    | '/brief/$token'
    | '/email/unsubscribe'
    | '/help/tax'
    | '/license/$token'
    | '/planner/$token'
    | '/supplier/$token'
    | '/track/$token'
    | '/vision/$token'
    | '/blog/'
    | '/api/assistant/stream'
    | '/lovable/email/suppression'
    | '/api/public/cron/deadline-reminders'
    | '/api/public/cron/fetch-daily-trends'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/cookies'
    | '/creative-partner'
    | '/dashboard'
    | '/labs'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/survey'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/auth/forgot'
    | '/blog/$slug'
    | '/brief/$token'
    | '/email/unsubscribe'
    | '/help/tax'
    | '/license/$token'
    | '/planner/$token'
    | '/supplier/$token'
    | '/track/$token'
    | '/vision/$token'
    | '/blog'
    | '/api/assistant/stream'
    | '/lovable/email/suppression'
    | '/api/public/cron/deadline-reminders'
    | '/api/public/cron/fetch-daily-trends'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/cookies'
    | '/creative-partner'
    | '/dashboard'
    | '/labs'
    | '/llms.txt'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/survey'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/auth/forgot'
    | '/blog/$slug'
    | '/brief/$token'
    | '/email/unsubscribe'
    | '/help/tax'
    | '/license/$token'
    | '/planner/$token'
    | '/supplier/$token'
    | '/track/$token'
    | '/vision/$token'
    | '/blog/'
    | '/api/assistant/stream'
    | '/lovable/email/suppression'
    | '/api/public/cron/deadline-reminders'
    | '/api/public/cron/fetch-daily-trends'
    | '/api/public/payments/webhook'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  CreativePartnerRoute: typeof CreativePartnerRoute
  DashboardRoute: typeof DashboardRoute
  LabsRoute: typeof LabsRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurveyRoute: typeof SurveyRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BriefTokenRoute: typeof BriefTokenRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  HelpTaxRoute: typeof HelpTaxRoute
  LicenseTokenRoute: typeof LicenseTokenRoute
  PlannerTokenRoute: typeof PlannerTokenRoute
  SupplierTokenRoute: typeof SupplierTokenRoute
  TrackTokenRoute: typeof TrackTokenRoute
  VisionTokenRoute: typeof VisionTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAssistantStreamRoute: typeof ApiAssistantStreamRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPublicCronDeadlineRemindersRoute: typeof ApiPublicCronDeadlineRemindersRoute
  ApiPublicCronFetchDailyTrendsRoute: typeof ApiPublicCronFetchDailyTrendsRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-partner': {
      id: '/creative-partner'
      path: '/creative-partner'
      fullPath: '/creative-partner'
      preLoaderRoute: typeof CreativePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/$token': {
      id: '/vision/$token'
      path: '/vision/$token'
      fullPath: '/vision/$token'
      preLoaderRoute: typeof VisionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/$token': {
      id: '/supplier/$token'
      path: '/supplier/$token'
      fullPath: '/supplier/$token'
      preLoaderRoute: typeof SupplierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/$token': {
      id: '/planner/$token'
      path: '/planner/$token'
      fullPath: '/planner/$token'
      preLoaderRoute: typeof PlannerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license/$token': {
      id: '/license/$token'
      path: '/license/$token'
      fullPath: '/license/$token'
      preLoaderRoute: typeof LicenseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help/tax': {
      id: '/help/tax'
      path: '/help/tax'
      fullPath: '/help/tax'
      preLoaderRoute: typeof HelpTaxRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$token': {
      id: '/brief/$token'
      path: '/brief/$token'
      fullPath: '/brief/$token'
      preLoaderRoute: typeof BriefTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/stream': {
      id: '/api/assistant/stream'
      path: '/api/assistant/stream'
      fullPath: '/api/assistant/stream'
      preLoaderRoute: typeof ApiAssistantStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fetch-daily-trends': {
      id: '/api/public/cron/fetch-daily-trends'
      path: '/api/public/cron/fetch-daily-trends'
      fullPath: '/api/public/cron/fetch-daily-trends'
      preLoaderRoute: typeof ApiPublicCronFetchDailyTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/deadline-reminders': {
      id: '/api/public/cron/deadline-reminders'
      path: '/api/public/cron/deadline-reminders'
      fullPath: '/api/public/cron/deadline-reminders'
      preLoaderRoute: typeof ApiPublicCronDeadlineRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRouteWithChildren,
  CookiesRoute: CookiesRoute,
  CreativePartnerRoute: CreativePartnerRoute,
  DashboardRoute: DashboardRoute,
  LabsRoute: LabsRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurveyRoute: SurveyRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  BriefTokenRoute: BriefTokenRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  HelpTaxRoute: HelpTaxRoute,
  LicenseTokenRoute: LicenseTokenRoute,
  PlannerTokenRoute: PlannerTokenRoute,
  SupplierTokenRoute: SupplierTokenRoute,
  TrackTokenRoute: TrackTokenRoute,
  VisionTokenRoute: VisionTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAssistantStreamRoute: ApiAssistantStreamRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPublicCronDeadlineRemindersRoute: ApiPublicCronDeadlineRemindersRoute,
  ApiPublicCronFetchDailyTrendsRoute: ApiPublicCronFetchDailyTrendsRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
