/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as UnsubscribeRouteImport } from './routes/unsubscribe'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as SurveyRouteImport } from './routes/survey'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ResearchRouteImport } from './routes/research'
import { Route as RefundRouteImport } from './routes/refund'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as MaintenanceRouteImport } from './routes/maintenance'
import { Route as LlmsDottxtRouteImport } from './routes/llms[.]txt'
import { Route as LineLinkRouteImport } from './routes/line-link'
import { Route as LabsRouteImport } from './routes/labs'
import { Route as InhouseRouteImport } from './routes/inhouse'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CreativePartnerRouteImport } from './routes/creative-partner'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as VisionTokenRouteImport } from './routes/vision.$token'
import { Route as TrackTokenRouteImport } from './routes/track.$token'
import { Route as SupplierTokenRouteImport } from './routes/supplier.$token'
import { Route as SignTokenRouteImport } from './routes/sign.$token'
import { Route as PlannerTokenRouteImport } from './routes/planner.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as PSlugRouteImport } from './routes/p.$slug'
import { Route as LicenseTokenRouteImport } from './routes/license.$token'
import { Route as InhouseOrgSlugRouteImport } from './routes/inhouse.$orgSlug'
import { Route as HelpTaxRouteImport } from './routes/help.tax'
import { Route as HelpQuotationsRouteImport } from './routes/help.quotations'
import { Route as HelpPlansRouteImport } from './routes/help.plans'
import { Route as HelpPaymentsRouteImport } from './routes/help.payments'
import { Route as HelpLineRouteImport } from './routes/help.line'
import { Route as HelpGettingStartedRouteImport } from './routes/help.getting-started'
import { Route as HelpBriefRouteImport } from './routes/help.brief'
import { Route as HelpBrandingRouteImport } from './routes/help.branding'
import { Route as EmailUnsubscribeRouteImport } from './routes/email/unsubscribe'
import { Route as DevStripeConnectUiRouteImport } from './routes/dev.stripe-connect-ui'
import { Route as BriefTokenRouteImport } from './routes/brief.$token'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AuthForgotRouteImport } from './routes/auth.forgot'
import { Route as AuthCallbackRouteImport } from './routes/auth.callback'
import { Route as TrackTokenCheckoutRouteImport } from './routes/track.$token.checkout'
import { Route as LovableEmailSuppressionRouteImport } from './routes/lovable/email/suppression'
import { Route as InhouseInviteTokenRouteImport } from './routes/inhouse.invite.$token'
import { Route as InhouseOrgSlugSettingsRouteImport } from './routes/inhouse.$orgSlug.settings'
import { Route as InhouseOrgSlugWorkspaceSlugRouteImport } from './routes/inhouse.$orgSlug.$workspaceSlug'
import { Route as ApiPublicCspReportRouteImport } from './routes/api/public/csp-report'
import { Route as ApiPaymentsCheckoutRouteImport } from './routes/api/payments/checkout'
import { Route as ApiAssistantStreamRouteImport } from './routes/api/assistant/stream'
import { Route as LovableEmailTransactionalSendRouteImport } from './routes/lovable/email/transactional/send'
import { Route as LovableEmailTransactionalPreviewRouteImport } from './routes/lovable/email/transactional/preview'
import { Route as LovableEmailQueueProcessRouteImport } from './routes/lovable/email/queue/process'
import { Route as LovableEmailAuthWebhookRouteImport } from './routes/lovable/email/auth/webhook'
import { Route as LovableEmailAuthPreviewRouteImport } from './routes/lovable/email/auth/preview'
import { Route as InhouseOrgSlugWorkspaceSlugTodosRouteImport } from './routes/inhouse.$orgSlug.$workspaceSlug.todos'
import { Route as InhouseOrgSlugWorkspaceSlugMonitorRouteImport } from './routes/inhouse.$orgSlug.$workspaceSlug.monitor'
import { Route as InhouseOrgSlugWorkspaceSlugKanbanRouteImport } from './routes/inhouse.$orgSlug.$workspaceSlug.kanban'
import { Route as InhouseOrgSlugWorkspaceSlugChatRouteImport } from './routes/inhouse.$orgSlug.$workspaceSlug.chat'
import { Route as InhouseOrgSlugWorkspaceSlugCanvasRouteImport } from './routes/inhouse.$orgSlug.$workspaceSlug.canvas'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicPaymentsClientCheckoutRouteImport } from './routes/api/public/payments/client-checkout'
import { Route as ApiPublicCronPaymentRemindersRouteImport } from './routes/api/public/cron/payment-reminders'
import { Route as ApiPublicCronMeetingCaptureCleanupRouteImport } from './routes/api/public/cron/meeting-capture-cleanup'
import { Route as ApiPublicCronFetchDailyTrendsRouteImport } from './routes/api/public/cron/fetch-daily-trends'
import { Route as ApiPublicCronDeadlineRemindersRouteImport } from './routes/api/public/cron/deadline-reminders'
import { Route as ApiPaymentsEscrowReleaseRouteImport } from './routes/api/payments/escrow/release'
import { Route as ApiPaymentsConnectOnboardRouteImport } from './routes/api/payments/connect/onboard'
import { Route as ApiPaymentsCashoutProcessRouteImport } from './routes/api/payments/cashout/process'

const UnsubscribeRoute = UnsubscribeRouteImport.update({
  id: '/unsubscribe',
  path: '/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const SurveyRoute = SurveyRouteImport.update({
  id: '/survey',
  path: '/survey',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ResearchRoute = ResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => rootRouteImport,
} as any)
const RefundRoute = RefundRouteImport.update({
  id: '/refund',
  path: '/refund',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const MaintenanceRoute = MaintenanceRouteImport.update({
  id: '/maintenance',
  path: '/maintenance',
  getParentRoute: () => rootRouteImport,
} as any)
const LlmsDottxtRoute = LlmsDottxtRouteImport.update({
  id: '/llms.txt',
  path: '/llms.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const LineLinkRoute = LineLinkRouteImport.update({
  id: '/line-link',
  path: '/line-link',
  getParentRoute: () => rootRouteImport,
} as any)
const LabsRoute = LabsRouteImport.update({
  id: '/labs',
  path: '/labs',
  getParentRoute: () => rootRouteImport,
} as any)
const InhouseRoute = InhouseRouteImport.update({
  id: '/inhouse',
  path: '/inhouse',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CreativePartnerRoute = CreativePartnerRouteImport.update({
  id: '/creative-partner',
  path: '/creative-partner',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/blog/',
  path: '/blog/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionTokenRoute = VisionTokenRouteImport.update({
  id: '/vision/$token',
  path: '/vision/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const TrackTokenRoute = TrackTokenRouteImport.update({
  id: '/track/$token',
  path: '/track/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SupplierTokenRoute = SupplierTokenRouteImport.update({
  id: '/supplier/$token',
  path: '/supplier/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const SignTokenRoute = SignTokenRouteImport.update({
  id: '/sign/$token',
  path: '/sign/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PlannerTokenRoute = PlannerTokenRouteImport.update({
  id: '/planner/$token',
  path: '/planner/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PSlugRoute = PSlugRouteImport.update({
  id: '/p/$slug',
  path: '/p/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const LicenseTokenRoute = LicenseTokenRouteImport.update({
  id: '/license/$token',
  path: '/license/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const InhouseOrgSlugRoute = InhouseOrgSlugRouteImport.update({
  id: '/$orgSlug',
  path: '/$orgSlug',
  getParentRoute: () => InhouseRoute,
} as any)
const HelpTaxRoute = HelpTaxRouteImport.update({
  id: '/tax',
  path: '/tax',
  getParentRoute: () => HelpRoute,
} as any)
const HelpQuotationsRoute = HelpQuotationsRouteImport.update({
  id: '/quotations',
  path: '/quotations',
  getParentRoute: () => HelpRoute,
} as any)
const HelpPlansRoute = HelpPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => HelpRoute,
} as any)
const HelpPaymentsRoute = HelpPaymentsRouteImport.update({
  id: '/payments',
  path: '/payments',
  getParentRoute: () => HelpRoute,
} as any)
const HelpLineRoute = HelpLineRouteImport.update({
  id: '/line',
  path: '/line',
  getParentRoute: () => HelpRoute,
} as any)
const HelpGettingStartedRoute = HelpGettingStartedRouteImport.update({
  id: '/getting-started',
  path: '/getting-started',
  getParentRoute: () => HelpRoute,
} as any)
const HelpBriefRoute = HelpBriefRouteImport.update({
  id: '/brief',
  path: '/brief',
  getParentRoute: () => HelpRoute,
} as any)
const HelpBrandingRoute = HelpBrandingRouteImport.update({
  id: '/branding',
  path: '/branding',
  getParentRoute: () => HelpRoute,
} as any)
const EmailUnsubscribeRoute = EmailUnsubscribeRouteImport.update({
  id: '/email/unsubscribe',
  path: '/email/unsubscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const DevStripeConnectUiRoute = DevStripeConnectUiRouteImport.update({
  id: '/dev/stripe-connect-ui',
  path: '/dev/stripe-connect-ui',
  getParentRoute: () => rootRouteImport,
} as any)
const BriefTokenRoute = BriefTokenRouteImport.update({
  id: '/brief/$token',
  path: '/brief/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/blog/$slug',
  path: '/blog/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthForgotRoute = AuthForgotRouteImport.update({
  id: '/forgot',
  path: '/forgot',
  getParentRoute: () => AuthRoute,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => AuthRoute,
} as any)
const TrackTokenCheckoutRoute = TrackTokenCheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => TrackTokenRoute,
} as any)
const LovableEmailSuppressionRoute = LovableEmailSuppressionRouteImport.update({
  id: '/lovable/email/suppression',
  path: '/lovable/email/suppression',
  getParentRoute: () => rootRouteImport,
} as any)
const InhouseInviteTokenRoute = InhouseInviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => InhouseRoute,
} as any)
const InhouseOrgSlugSettingsRoute = InhouseOrgSlugSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => InhouseOrgSlugRoute,
} as any)
const InhouseOrgSlugWorkspaceSlugRoute =
  InhouseOrgSlugWorkspaceSlugRouteImport.update({
    id: '/$workspaceSlug',
    path: '/$workspaceSlug',
    getParentRoute: () => InhouseOrgSlugRoute,
  } as any)
const ApiPublicCspReportRoute = ApiPublicCspReportRouteImport.update({
  id: '/api/public/csp-report',
  path: '/api/public/csp-report',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPaymentsCheckoutRoute = ApiPaymentsCheckoutRouteImport.update({
  id: '/api/payments/checkout',
  path: '/api/payments/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAssistantStreamRoute = ApiAssistantStreamRouteImport.update({
  id: '/api/assistant/stream',
  path: '/api/assistant/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailTransactionalSendRoute =
  LovableEmailTransactionalSendRouteImport.update({
    id: '/lovable/email/transactional/send',
    path: '/lovable/email/transactional/send',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailTransactionalPreviewRoute =
  LovableEmailTransactionalPreviewRouteImport.update({
    id: '/lovable/email/transactional/preview',
    path: '/lovable/email/transactional/preview',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailQueueProcessRoute =
  LovableEmailQueueProcessRouteImport.update({
    id: '/lovable/email/queue/process',
    path: '/lovable/email/queue/process',
    getParentRoute: () => rootRouteImport,
  } as any)
const LovableEmailAuthWebhookRoute = LovableEmailAuthWebhookRouteImport.update({
  id: '/lovable/email/auth/webhook',
  path: '/lovable/email/auth/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const LovableEmailAuthPreviewRoute = LovableEmailAuthPreviewRouteImport.update({
  id: '/lovable/email/auth/preview',
  path: '/lovable/email/auth/preview',
  getParentRoute: () => rootRouteImport,
} as any)
const InhouseOrgSlugWorkspaceSlugTodosRoute =
  InhouseOrgSlugWorkspaceSlugTodosRouteImport.update({
    id: '/todos',
    path: '/todos',
    getParentRoute: () => InhouseOrgSlugWorkspaceSlugRoute,
  } as any)
const InhouseOrgSlugWorkspaceSlugMonitorRoute =
  InhouseOrgSlugWorkspaceSlugMonitorRouteImport.update({
    id: '/monitor',
    path: '/monitor',
    getParentRoute: () => InhouseOrgSlugWorkspaceSlugRoute,
  } as any)
const InhouseOrgSlugWorkspaceSlugKanbanRoute =
  InhouseOrgSlugWorkspaceSlugKanbanRouteImport.update({
    id: '/kanban',
    path: '/kanban',
    getParentRoute: () => InhouseOrgSlugWorkspaceSlugRoute,
  } as any)
const InhouseOrgSlugWorkspaceSlugChatRoute =
  InhouseOrgSlugWorkspaceSlugChatRouteImport.update({
    id: '/chat',
    path: '/chat',
    getParentRoute: () => InhouseOrgSlugWorkspaceSlugRoute,
  } as any)
const InhouseOrgSlugWorkspaceSlugCanvasRoute =
  InhouseOrgSlugWorkspaceSlugCanvasRouteImport.update({
    id: '/canvas',
    path: '/canvas',
    getParentRoute: () => InhouseOrgSlugWorkspaceSlugRoute,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsClientCheckoutRoute =
  ApiPublicPaymentsClientCheckoutRouteImport.update({
    id: '/api/public/payments/client-checkout',
    path: '/api/public/payments/client-checkout',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronPaymentRemindersRoute =
  ApiPublicCronPaymentRemindersRouteImport.update({
    id: '/api/public/cron/payment-reminders',
    path: '/api/public/cron/payment-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronMeetingCaptureCleanupRoute =
  ApiPublicCronMeetingCaptureCleanupRouteImport.update({
    id: '/api/public/cron/meeting-capture-cleanup',
    path: '/api/public/cron/meeting-capture-cleanup',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronFetchDailyTrendsRoute =
  ApiPublicCronFetchDailyTrendsRouteImport.update({
    id: '/api/public/cron/fetch-daily-trends',
    path: '/api/public/cron/fetch-daily-trends',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicCronDeadlineRemindersRoute =
  ApiPublicCronDeadlineRemindersRouteImport.update({
    id: '/api/public/cron/deadline-reminders',
    path: '/api/public/cron/deadline-reminders',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsEscrowReleaseRoute =
  ApiPaymentsEscrowReleaseRouteImport.update({
    id: '/api/payments/escrow/release',
    path: '/api/payments/escrow/release',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsConnectOnboardRoute =
  ApiPaymentsConnectOnboardRouteImport.update({
    id: '/api/payments/connect/onboard',
    path: '/api/payments/connect/onboard',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPaymentsCashoutProcessRoute =
  ApiPaymentsCashoutProcessRouteImport.update({
    id: '/api/payments/cashout/process',
    path: '/api/payments/cashout/process',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/creative-partner': typeof CreativePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRouteWithChildren
  '/inhouse': typeof InhouseRouteWithChildren
  '/labs': typeof LabsRoute
  '/line-link': typeof LineLinkRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brief/$token': typeof BriefTokenRoute
  '/dev/stripe-connect-ui': typeof DevStripeConnectUiRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/branding': typeof HelpBrandingRoute
  '/help/brief': typeof HelpBriefRoute
  '/help/getting-started': typeof HelpGettingStartedRoute
  '/help/line': typeof HelpLineRoute
  '/help/payments': typeof HelpPaymentsRoute
  '/help/plans': typeof HelpPlansRoute
  '/help/quotations': typeof HelpQuotationsRoute
  '/help/tax': typeof HelpTaxRoute
  '/inhouse/$orgSlug': typeof InhouseOrgSlugRouteWithChildren
  '/license/$token': typeof LicenseTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/planner/$token': typeof PlannerTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/track/$token': typeof TrackTokenRouteWithChildren
  '/vision/$token': typeof VisionTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/api/assistant/stream': typeof ApiAssistantStreamRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/inhouse/$orgSlug/$workspaceSlug': typeof InhouseOrgSlugWorkspaceSlugRouteWithChildren
  '/inhouse/$orgSlug/settings': typeof InhouseOrgSlugSettingsRoute
  '/inhouse/invite/$token': typeof InhouseInviteTokenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/track/$token/checkout': typeof TrackTokenCheckoutRoute
  '/api/payments/cashout/process': typeof ApiPaymentsCashoutProcessRoute
  '/api/payments/connect/onboard': typeof ApiPaymentsConnectOnboardRoute
  '/api/payments/escrow/release': typeof ApiPaymentsEscrowReleaseRoute
  '/api/public/cron/deadline-reminders': typeof ApiPublicCronDeadlineRemindersRoute
  '/api/public/cron/fetch-daily-trends': typeof ApiPublicCronFetchDailyTrendsRoute
  '/api/public/cron/meeting-capture-cleanup': typeof ApiPublicCronMeetingCaptureCleanupRoute
  '/api/public/cron/payment-reminders': typeof ApiPublicCronPaymentRemindersRoute
  '/api/public/payments/client-checkout': typeof ApiPublicPaymentsClientCheckoutRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/inhouse/$orgSlug/$workspaceSlug/canvas': typeof InhouseOrgSlugWorkspaceSlugCanvasRoute
  '/inhouse/$orgSlug/$workspaceSlug/chat': typeof InhouseOrgSlugWorkspaceSlugChatRoute
  '/inhouse/$orgSlug/$workspaceSlug/kanban': typeof InhouseOrgSlugWorkspaceSlugKanbanRoute
  '/inhouse/$orgSlug/$workspaceSlug/monitor': typeof InhouseOrgSlugWorkspaceSlugMonitorRoute
  '/inhouse/$orgSlug/$workspaceSlug/todos': typeof InhouseOrgSlugWorkspaceSlugTodosRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/creative-partner': typeof CreativePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRouteWithChildren
  '/inhouse': typeof InhouseRouteWithChildren
  '/labs': typeof LabsRoute
  '/line-link': typeof LineLinkRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brief/$token': typeof BriefTokenRoute
  '/dev/stripe-connect-ui': typeof DevStripeConnectUiRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/branding': typeof HelpBrandingRoute
  '/help/brief': typeof HelpBriefRoute
  '/help/getting-started': typeof HelpGettingStartedRoute
  '/help/line': typeof HelpLineRoute
  '/help/payments': typeof HelpPaymentsRoute
  '/help/plans': typeof HelpPlansRoute
  '/help/quotations': typeof HelpQuotationsRoute
  '/help/tax': typeof HelpTaxRoute
  '/inhouse/$orgSlug': typeof InhouseOrgSlugRouteWithChildren
  '/license/$token': typeof LicenseTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/planner/$token': typeof PlannerTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/track/$token': typeof TrackTokenRouteWithChildren
  '/vision/$token': typeof VisionTokenRoute
  '/blog': typeof BlogIndexRoute
  '/api/assistant/stream': typeof ApiAssistantStreamRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/inhouse/$orgSlug/$workspaceSlug': typeof InhouseOrgSlugWorkspaceSlugRouteWithChildren
  '/inhouse/$orgSlug/settings': typeof InhouseOrgSlugSettingsRoute
  '/inhouse/invite/$token': typeof InhouseInviteTokenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/track/$token/checkout': typeof TrackTokenCheckoutRoute
  '/api/payments/cashout/process': typeof ApiPaymentsCashoutProcessRoute
  '/api/payments/connect/onboard': typeof ApiPaymentsConnectOnboardRoute
  '/api/payments/escrow/release': typeof ApiPaymentsEscrowReleaseRoute
  '/api/public/cron/deadline-reminders': typeof ApiPublicCronDeadlineRemindersRoute
  '/api/public/cron/fetch-daily-trends': typeof ApiPublicCronFetchDailyTrendsRoute
  '/api/public/cron/meeting-capture-cleanup': typeof ApiPublicCronMeetingCaptureCleanupRoute
  '/api/public/cron/payment-reminders': typeof ApiPublicCronPaymentRemindersRoute
  '/api/public/payments/client-checkout': typeof ApiPublicPaymentsClientCheckoutRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/inhouse/$orgSlug/$workspaceSlug/canvas': typeof InhouseOrgSlugWorkspaceSlugCanvasRoute
  '/inhouse/$orgSlug/$workspaceSlug/chat': typeof InhouseOrgSlugWorkspaceSlugChatRoute
  '/inhouse/$orgSlug/$workspaceSlug/kanban': typeof InhouseOrgSlugWorkspaceSlugKanbanRoute
  '/inhouse/$orgSlug/$workspaceSlug/monitor': typeof InhouseOrgSlugWorkspaceSlugMonitorRoute
  '/inhouse/$orgSlug/$workspaceSlug/todos': typeof InhouseOrgSlugWorkspaceSlugTodosRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRouteWithChildren
  '/cookies': typeof CookiesRoute
  '/creative-partner': typeof CreativePartnerRoute
  '/dashboard': typeof DashboardRoute
  '/help': typeof HelpRouteWithChildren
  '/inhouse': typeof InhouseRouteWithChildren
  '/labs': typeof LabsRoute
  '/line-link': typeof LineLinkRoute
  '/llms.txt': typeof LlmsDottxtRoute
  '/maintenance': typeof MaintenanceRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/refund': typeof RefundRoute
  '/research': typeof ResearchRoute
  '/reset-password': typeof ResetPasswordRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/survey': typeof SurveyRoute
  '/terms': typeof TermsRoute
  '/unsubscribe': typeof UnsubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/auth/forgot': typeof AuthForgotRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/brief/$token': typeof BriefTokenRoute
  '/dev/stripe-connect-ui': typeof DevStripeConnectUiRoute
  '/email/unsubscribe': typeof EmailUnsubscribeRoute
  '/help/branding': typeof HelpBrandingRoute
  '/help/brief': typeof HelpBriefRoute
  '/help/getting-started': typeof HelpGettingStartedRoute
  '/help/line': typeof HelpLineRoute
  '/help/payments': typeof HelpPaymentsRoute
  '/help/plans': typeof HelpPlansRoute
  '/help/quotations': typeof HelpQuotationsRoute
  '/help/tax': typeof HelpTaxRoute
  '/inhouse/$orgSlug': typeof InhouseOrgSlugRouteWithChildren
  '/license/$token': typeof LicenseTokenRoute
  '/p/$slug': typeof PSlugRoute
  '/pay/$token': typeof PayTokenRoute
  '/planner/$token': typeof PlannerTokenRoute
  '/sign/$token': typeof SignTokenRoute
  '/supplier/$token': typeof SupplierTokenRoute
  '/track/$token': typeof TrackTokenRouteWithChildren
  '/vision/$token': typeof VisionTokenRoute
  '/blog/': typeof BlogIndexRoute
  '/api/assistant/stream': typeof ApiAssistantStreamRoute
  '/api/payments/checkout': typeof ApiPaymentsCheckoutRoute
  '/api/public/csp-report': typeof ApiPublicCspReportRoute
  '/inhouse/$orgSlug/$workspaceSlug': typeof InhouseOrgSlugWorkspaceSlugRouteWithChildren
  '/inhouse/$orgSlug/settings': typeof InhouseOrgSlugSettingsRoute
  '/inhouse/invite/$token': typeof InhouseInviteTokenRoute
  '/lovable/email/suppression': typeof LovableEmailSuppressionRoute
  '/track/$token/checkout': typeof TrackTokenCheckoutRoute
  '/api/payments/cashout/process': typeof ApiPaymentsCashoutProcessRoute
  '/api/payments/connect/onboard': typeof ApiPaymentsConnectOnboardRoute
  '/api/payments/escrow/release': typeof ApiPaymentsEscrowReleaseRoute
  '/api/public/cron/deadline-reminders': typeof ApiPublicCronDeadlineRemindersRoute
  '/api/public/cron/fetch-daily-trends': typeof ApiPublicCronFetchDailyTrendsRoute
  '/api/public/cron/meeting-capture-cleanup': typeof ApiPublicCronMeetingCaptureCleanupRoute
  '/api/public/cron/payment-reminders': typeof ApiPublicCronPaymentRemindersRoute
  '/api/public/payments/client-checkout': typeof ApiPublicPaymentsClientCheckoutRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/inhouse/$orgSlug/$workspaceSlug/canvas': typeof InhouseOrgSlugWorkspaceSlugCanvasRoute
  '/inhouse/$orgSlug/$workspaceSlug/chat': typeof InhouseOrgSlugWorkspaceSlugChatRoute
  '/inhouse/$orgSlug/$workspaceSlug/kanban': typeof InhouseOrgSlugWorkspaceSlugKanbanRoute
  '/inhouse/$orgSlug/$workspaceSlug/monitor': typeof InhouseOrgSlugWorkspaceSlugMonitorRoute
  '/inhouse/$orgSlug/$workspaceSlug/todos': typeof InhouseOrgSlugWorkspaceSlugTodosRoute
  '/lovable/email/auth/preview': typeof LovableEmailAuthPreviewRoute
  '/lovable/email/auth/webhook': typeof LovableEmailAuthWebhookRoute
  '/lovable/email/queue/process': typeof LovableEmailQueueProcessRoute
  '/lovable/email/transactional/preview': typeof LovableEmailTransactionalPreviewRoute
  '/lovable/email/transactional/send': typeof LovableEmailTransactionalSendRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/cookies'
    | '/creative-partner'
    | '/dashboard'
    | '/help'
    | '/inhouse'
    | '/labs'
    | '/line-link'
    | '/llms.txt'
    | '/maintenance'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/research'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/survey'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/auth/forgot'
    | '/blog/$slug'
    | '/brief/$token'
    | '/dev/stripe-connect-ui'
    | '/email/unsubscribe'
    | '/help/branding'
    | '/help/brief'
    | '/help/getting-started'
    | '/help/line'
    | '/help/payments'
    | '/help/plans'
    | '/help/quotations'
    | '/help/tax'
    | '/inhouse/$orgSlug'
    | '/license/$token'
    | '/p/$slug'
    | '/pay/$token'
    | '/planner/$token'
    | '/sign/$token'
    | '/supplier/$token'
    | '/track/$token'
    | '/vision/$token'
    | '/blog/'
    | '/api/assistant/stream'
    | '/api/payments/checkout'
    | '/api/public/csp-report'
    | '/inhouse/$orgSlug/$workspaceSlug'
    | '/inhouse/$orgSlug/settings'
    | '/inhouse/invite/$token'
    | '/lovable/email/suppression'
    | '/track/$token/checkout'
    | '/api/payments/cashout/process'
    | '/api/payments/connect/onboard'
    | '/api/payments/escrow/release'
    | '/api/public/cron/deadline-reminders'
    | '/api/public/cron/fetch-daily-trends'
    | '/api/public/cron/meeting-capture-cleanup'
    | '/api/public/cron/payment-reminders'
    | '/api/public/payments/client-checkout'
    | '/api/public/payments/webhook'
    | '/inhouse/$orgSlug/$workspaceSlug/canvas'
    | '/inhouse/$orgSlug/$workspaceSlug/chat'
    | '/inhouse/$orgSlug/$workspaceSlug/kanban'
    | '/inhouse/$orgSlug/$workspaceSlug/monitor'
    | '/inhouse/$orgSlug/$workspaceSlug/todos'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/cookies'
    | '/creative-partner'
    | '/dashboard'
    | '/help'
    | '/inhouse'
    | '/labs'
    | '/line-link'
    | '/llms.txt'
    | '/maintenance'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/research'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/survey'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/auth/forgot'
    | '/blog/$slug'
    | '/brief/$token'
    | '/dev/stripe-connect-ui'
    | '/email/unsubscribe'
    | '/help/branding'
    | '/help/brief'
    | '/help/getting-started'
    | '/help/line'
    | '/help/payments'
    | '/help/plans'
    | '/help/quotations'
    | '/help/tax'
    | '/inhouse/$orgSlug'
    | '/license/$token'
    | '/p/$slug'
    | '/pay/$token'
    | '/planner/$token'
    | '/sign/$token'
    | '/supplier/$token'
    | '/track/$token'
    | '/vision/$token'
    | '/blog'
    | '/api/assistant/stream'
    | '/api/payments/checkout'
    | '/api/public/csp-report'
    | '/inhouse/$orgSlug/$workspaceSlug'
    | '/inhouse/$orgSlug/settings'
    | '/inhouse/invite/$token'
    | '/lovable/email/suppression'
    | '/track/$token/checkout'
    | '/api/payments/cashout/process'
    | '/api/payments/connect/onboard'
    | '/api/payments/escrow/release'
    | '/api/public/cron/deadline-reminders'
    | '/api/public/cron/fetch-daily-trends'
    | '/api/public/cron/meeting-capture-cleanup'
    | '/api/public/cron/payment-reminders'
    | '/api/public/payments/client-checkout'
    | '/api/public/payments/webhook'
    | '/inhouse/$orgSlug/$workspaceSlug/canvas'
    | '/inhouse/$orgSlug/$workspaceSlug/chat'
    | '/inhouse/$orgSlug/$workspaceSlug/kanban'
    | '/inhouse/$orgSlug/$workspaceSlug/monitor'
    | '/inhouse/$orgSlug/$workspaceSlug/todos'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/cookies'
    | '/creative-partner'
    | '/dashboard'
    | '/help'
    | '/inhouse'
    | '/labs'
    | '/line-link'
    | '/llms.txt'
    | '/maintenance'
    | '/pricing'
    | '/privacy'
    | '/refund'
    | '/research'
    | '/reset-password'
    | '/robots.txt'
    | '/sitemap.xml'
    | '/survey'
    | '/terms'
    | '/unsubscribe'
    | '/auth/callback'
    | '/auth/forgot'
    | '/blog/$slug'
    | '/brief/$token'
    | '/dev/stripe-connect-ui'
    | '/email/unsubscribe'
    | '/help/branding'
    | '/help/brief'
    | '/help/getting-started'
    | '/help/line'
    | '/help/payments'
    | '/help/plans'
    | '/help/quotations'
    | '/help/tax'
    | '/inhouse/$orgSlug'
    | '/license/$token'
    | '/p/$slug'
    | '/pay/$token'
    | '/planner/$token'
    | '/sign/$token'
    | '/supplier/$token'
    | '/track/$token'
    | '/vision/$token'
    | '/blog/'
    | '/api/assistant/stream'
    | '/api/payments/checkout'
    | '/api/public/csp-report'
    | '/inhouse/$orgSlug/$workspaceSlug'
    | '/inhouse/$orgSlug/settings'
    | '/inhouse/invite/$token'
    | '/lovable/email/suppression'
    | '/track/$token/checkout'
    | '/api/payments/cashout/process'
    | '/api/payments/connect/onboard'
    | '/api/payments/escrow/release'
    | '/api/public/cron/deadline-reminders'
    | '/api/public/cron/fetch-daily-trends'
    | '/api/public/cron/meeting-capture-cleanup'
    | '/api/public/cron/payment-reminders'
    | '/api/public/payments/client-checkout'
    | '/api/public/payments/webhook'
    | '/inhouse/$orgSlug/$workspaceSlug/canvas'
    | '/inhouse/$orgSlug/$workspaceSlug/chat'
    | '/inhouse/$orgSlug/$workspaceSlug/kanban'
    | '/inhouse/$orgSlug/$workspaceSlug/monitor'
    | '/inhouse/$orgSlug/$workspaceSlug/todos'
    | '/lovable/email/auth/preview'
    | '/lovable/email/auth/webhook'
    | '/lovable/email/queue/process'
    | '/lovable/email/transactional/preview'
    | '/lovable/email/transactional/send'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRouteWithChildren
  CookiesRoute: typeof CookiesRoute
  CreativePartnerRoute: typeof CreativePartnerRoute
  DashboardRoute: typeof DashboardRoute
  HelpRoute: typeof HelpRouteWithChildren
  InhouseRoute: typeof InhouseRouteWithChildren
  LabsRoute: typeof LabsRoute
  LineLinkRoute: typeof LineLinkRoute
  LlmsDottxtRoute: typeof LlmsDottxtRoute
  MaintenanceRoute: typeof MaintenanceRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  RefundRoute: typeof RefundRoute
  ResearchRoute: typeof ResearchRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SurveyRoute: typeof SurveyRoute
  TermsRoute: typeof TermsRoute
  UnsubscribeRoute: typeof UnsubscribeRoute
  BlogSlugRoute: typeof BlogSlugRoute
  BriefTokenRoute: typeof BriefTokenRoute
  DevStripeConnectUiRoute: typeof DevStripeConnectUiRoute
  EmailUnsubscribeRoute: typeof EmailUnsubscribeRoute
  LicenseTokenRoute: typeof LicenseTokenRoute
  PSlugRoute: typeof PSlugRoute
  PayTokenRoute: typeof PayTokenRoute
  PlannerTokenRoute: typeof PlannerTokenRoute
  SignTokenRoute: typeof SignTokenRoute
  SupplierTokenRoute: typeof SupplierTokenRoute
  TrackTokenRoute: typeof TrackTokenRouteWithChildren
  VisionTokenRoute: typeof VisionTokenRoute
  BlogIndexRoute: typeof BlogIndexRoute
  ApiAssistantStreamRoute: typeof ApiAssistantStreamRoute
  ApiPaymentsCheckoutRoute: typeof ApiPaymentsCheckoutRoute
  ApiPublicCspReportRoute: typeof ApiPublicCspReportRoute
  LovableEmailSuppressionRoute: typeof LovableEmailSuppressionRoute
  ApiPaymentsCashoutProcessRoute: typeof ApiPaymentsCashoutProcessRoute
  ApiPaymentsConnectOnboardRoute: typeof ApiPaymentsConnectOnboardRoute
  ApiPaymentsEscrowReleaseRoute: typeof ApiPaymentsEscrowReleaseRoute
  ApiPublicCronDeadlineRemindersRoute: typeof ApiPublicCronDeadlineRemindersRoute
  ApiPublicCronFetchDailyTrendsRoute: typeof ApiPublicCronFetchDailyTrendsRoute
  ApiPublicCronMeetingCaptureCleanupRoute: typeof ApiPublicCronMeetingCaptureCleanupRoute
  ApiPublicCronPaymentRemindersRoute: typeof ApiPublicCronPaymentRemindersRoute
  ApiPublicPaymentsClientCheckoutRoute: typeof ApiPublicPaymentsClientCheckoutRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  LovableEmailAuthPreviewRoute: typeof LovableEmailAuthPreviewRoute
  LovableEmailAuthWebhookRoute: typeof LovableEmailAuthWebhookRoute
  LovableEmailQueueProcessRoute: typeof LovableEmailQueueProcessRoute
  LovableEmailTransactionalPreviewRoute: typeof LovableEmailTransactionalPreviewRoute
  LovableEmailTransactionalSendRoute: typeof LovableEmailTransactionalSendRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/unsubscribe': {
      id: '/unsubscribe'
      path: '/unsubscribe'
      fullPath: '/unsubscribe'
      preLoaderRoute: typeof UnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/survey': {
      id: '/survey'
      path: '/survey'
      fullPath: '/survey'
      preLoaderRoute: typeof SurveyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/research': {
      id: '/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof ResearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/refund': {
      id: '/refund'
      path: '/refund'
      fullPath: '/refund'
      preLoaderRoute: typeof RefundRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/maintenance': {
      id: '/maintenance'
      path: '/maintenance'
      fullPath: '/maintenance'
      preLoaderRoute: typeof MaintenanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/llms.txt': {
      id: '/llms.txt'
      path: '/llms.txt'
      fullPath: '/llms.txt'
      preLoaderRoute: typeof LlmsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/line-link': {
      id: '/line-link'
      path: '/line-link'
      fullPath: '/line-link'
      preLoaderRoute: typeof LineLinkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/labs': {
      id: '/labs'
      path: '/labs'
      fullPath: '/labs'
      preLoaderRoute: typeof LabsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inhouse': {
      id: '/inhouse'
      path: '/inhouse'
      fullPath: '/inhouse'
      preLoaderRoute: typeof InhouseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/creative-partner': {
      id: '/creative-partner'
      path: '/creative-partner'
      fullPath: '/creative-partner'
      preLoaderRoute: typeof CreativePartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/': {
      id: '/blog/'
      path: '/blog'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision/$token': {
      id: '/vision/$token'
      path: '/vision/$token'
      fullPath: '/vision/$token'
      preLoaderRoute: typeof VisionTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/track/$token': {
      id: '/track/$token'
      path: '/track/$token'
      fullPath: '/track/$token'
      preLoaderRoute: typeof TrackTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supplier/$token': {
      id: '/supplier/$token'
      path: '/supplier/$token'
      fullPath: '/supplier/$token'
      preLoaderRoute: typeof SupplierTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign/$token': {
      id: '/sign/$token'
      path: '/sign/$token'
      fullPath: '/sign/$token'
      preLoaderRoute: typeof SignTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planner/$token': {
      id: '/planner/$token'
      path: '/planner/$token'
      fullPath: '/planner/$token'
      preLoaderRoute: typeof PlannerTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$slug': {
      id: '/p/$slug'
      path: '/p/$slug'
      fullPath: '/p/$slug'
      preLoaderRoute: typeof PSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/license/$token': {
      id: '/license/$token'
      path: '/license/$token'
      fullPath: '/license/$token'
      preLoaderRoute: typeof LicenseTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inhouse/$orgSlug': {
      id: '/inhouse/$orgSlug'
      path: '/$orgSlug'
      fullPath: '/inhouse/$orgSlug'
      preLoaderRoute: typeof InhouseOrgSlugRouteImport
      parentRoute: typeof InhouseRoute
    }
    '/help/tax': {
      id: '/help/tax'
      path: '/tax'
      fullPath: '/help/tax'
      preLoaderRoute: typeof HelpTaxRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/quotations': {
      id: '/help/quotations'
      path: '/quotations'
      fullPath: '/help/quotations'
      preLoaderRoute: typeof HelpQuotationsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/plans': {
      id: '/help/plans'
      path: '/plans'
      fullPath: '/help/plans'
      preLoaderRoute: typeof HelpPlansRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/payments': {
      id: '/help/payments'
      path: '/payments'
      fullPath: '/help/payments'
      preLoaderRoute: typeof HelpPaymentsRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/line': {
      id: '/help/line'
      path: '/line'
      fullPath: '/help/line'
      preLoaderRoute: typeof HelpLineRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/getting-started': {
      id: '/help/getting-started'
      path: '/getting-started'
      fullPath: '/help/getting-started'
      preLoaderRoute: typeof HelpGettingStartedRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/brief': {
      id: '/help/brief'
      path: '/brief'
      fullPath: '/help/brief'
      preLoaderRoute: typeof HelpBriefRouteImport
      parentRoute: typeof HelpRoute
    }
    '/help/branding': {
      id: '/help/branding'
      path: '/branding'
      fullPath: '/help/branding'
      preLoaderRoute: typeof HelpBrandingRouteImport
      parentRoute: typeof HelpRoute
    }
    '/email/unsubscribe': {
      id: '/email/unsubscribe'
      path: '/email/unsubscribe'
      fullPath: '/email/unsubscribe'
      preLoaderRoute: typeof EmailUnsubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dev/stripe-connect-ui': {
      id: '/dev/stripe-connect-ui'
      path: '/dev/stripe-connect-ui'
      fullPath: '/dev/stripe-connect-ui'
      preLoaderRoute: typeof DevStripeConnectUiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/brief/$token': {
      id: '/brief/$token'
      path: '/brief/$token'
      fullPath: '/brief/$token'
      preLoaderRoute: typeof BriefTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/blog/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/forgot': {
      id: '/auth/forgot'
      path: '/forgot'
      fullPath: '/auth/forgot'
      preLoaderRoute: typeof AuthForgotRouteImport
      parentRoute: typeof AuthRoute
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof AuthRoute
    }
    '/track/$token/checkout': {
      id: '/track/$token/checkout'
      path: '/checkout'
      fullPath: '/track/$token/checkout'
      preLoaderRoute: typeof TrackTokenCheckoutRouteImport
      parentRoute: typeof TrackTokenRoute
    }
    '/lovable/email/suppression': {
      id: '/lovable/email/suppression'
      path: '/lovable/email/suppression'
      fullPath: '/lovable/email/suppression'
      preLoaderRoute: typeof LovableEmailSuppressionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inhouse/invite/$token': {
      id: '/inhouse/invite/$token'
      path: '/invite/$token'
      fullPath: '/inhouse/invite/$token'
      preLoaderRoute: typeof InhouseInviteTokenRouteImport
      parentRoute: typeof InhouseRoute
    }
    '/inhouse/$orgSlug/settings': {
      id: '/inhouse/$orgSlug/settings'
      path: '/settings'
      fullPath: '/inhouse/$orgSlug/settings'
      preLoaderRoute: typeof InhouseOrgSlugSettingsRouteImport
      parentRoute: typeof InhouseOrgSlugRoute
    }
    '/inhouse/$orgSlug/$workspaceSlug': {
      id: '/inhouse/$orgSlug/$workspaceSlug'
      path: '/$workspaceSlug'
      fullPath: '/inhouse/$orgSlug/$workspaceSlug'
      preLoaderRoute: typeof InhouseOrgSlugWorkspaceSlugRouteImport
      parentRoute: typeof InhouseOrgSlugRoute
    }
    '/api/public/csp-report': {
      id: '/api/public/csp-report'
      path: '/api/public/csp-report'
      fullPath: '/api/public/csp-report'
      preLoaderRoute: typeof ApiPublicCspReportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/checkout': {
      id: '/api/payments/checkout'
      path: '/api/payments/checkout'
      fullPath: '/api/payments/checkout'
      preLoaderRoute: typeof ApiPaymentsCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/assistant/stream': {
      id: '/api/assistant/stream'
      path: '/api/assistant/stream'
      fullPath: '/api/assistant/stream'
      preLoaderRoute: typeof ApiAssistantStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/send': {
      id: '/lovable/email/transactional/send'
      path: '/lovable/email/transactional/send'
      fullPath: '/lovable/email/transactional/send'
      preLoaderRoute: typeof LovableEmailTransactionalSendRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/transactional/preview': {
      id: '/lovable/email/transactional/preview'
      path: '/lovable/email/transactional/preview'
      fullPath: '/lovable/email/transactional/preview'
      preLoaderRoute: typeof LovableEmailTransactionalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/queue/process': {
      id: '/lovable/email/queue/process'
      path: '/lovable/email/queue/process'
      fullPath: '/lovable/email/queue/process'
      preLoaderRoute: typeof LovableEmailQueueProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/webhook': {
      id: '/lovable/email/auth/webhook'
      path: '/lovable/email/auth/webhook'
      fullPath: '/lovable/email/auth/webhook'
      preLoaderRoute: typeof LovableEmailAuthWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lovable/email/auth/preview': {
      id: '/lovable/email/auth/preview'
      path: '/lovable/email/auth/preview'
      fullPath: '/lovable/email/auth/preview'
      preLoaderRoute: typeof LovableEmailAuthPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/inhouse/$orgSlug/$workspaceSlug/todos': {
      id: '/inhouse/$orgSlug/$workspaceSlug/todos'
      path: '/todos'
      fullPath: '/inhouse/$orgSlug/$workspaceSlug/todos'
      preLoaderRoute: typeof InhouseOrgSlugWorkspaceSlugTodosRouteImport
      parentRoute: typeof InhouseOrgSlugWorkspaceSlugRoute
    }
    '/inhouse/$orgSlug/$workspaceSlug/monitor': {
      id: '/inhouse/$orgSlug/$workspaceSlug/monitor'
      path: '/monitor'
      fullPath: '/inhouse/$orgSlug/$workspaceSlug/monitor'
      preLoaderRoute: typeof InhouseOrgSlugWorkspaceSlugMonitorRouteImport
      parentRoute: typeof InhouseOrgSlugWorkspaceSlugRoute
    }
    '/inhouse/$orgSlug/$workspaceSlug/kanban': {
      id: '/inhouse/$orgSlug/$workspaceSlug/kanban'
      path: '/kanban'
      fullPath: '/inhouse/$orgSlug/$workspaceSlug/kanban'
      preLoaderRoute: typeof InhouseOrgSlugWorkspaceSlugKanbanRouteImport
      parentRoute: typeof InhouseOrgSlugWorkspaceSlugRoute
    }
    '/inhouse/$orgSlug/$workspaceSlug/chat': {
      id: '/inhouse/$orgSlug/$workspaceSlug/chat'
      path: '/chat'
      fullPath: '/inhouse/$orgSlug/$workspaceSlug/chat'
      preLoaderRoute: typeof InhouseOrgSlugWorkspaceSlugChatRouteImport
      parentRoute: typeof InhouseOrgSlugWorkspaceSlugRoute
    }
    '/inhouse/$orgSlug/$workspaceSlug/canvas': {
      id: '/inhouse/$orgSlug/$workspaceSlug/canvas'
      path: '/canvas'
      fullPath: '/inhouse/$orgSlug/$workspaceSlug/canvas'
      preLoaderRoute: typeof InhouseOrgSlugWorkspaceSlugCanvasRouteImport
      parentRoute: typeof InhouseOrgSlugWorkspaceSlugRoute
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/client-checkout': {
      id: '/api/public/payments/client-checkout'
      path: '/api/public/payments/client-checkout'
      fullPath: '/api/public/payments/client-checkout'
      preLoaderRoute: typeof ApiPublicPaymentsClientCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/payment-reminders': {
      id: '/api/public/cron/payment-reminders'
      path: '/api/public/cron/payment-reminders'
      fullPath: '/api/public/cron/payment-reminders'
      preLoaderRoute: typeof ApiPublicCronPaymentRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/meeting-capture-cleanup': {
      id: '/api/public/cron/meeting-capture-cleanup'
      path: '/api/public/cron/meeting-capture-cleanup'
      fullPath: '/api/public/cron/meeting-capture-cleanup'
      preLoaderRoute: typeof ApiPublicCronMeetingCaptureCleanupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/fetch-daily-trends': {
      id: '/api/public/cron/fetch-daily-trends'
      path: '/api/public/cron/fetch-daily-trends'
      fullPath: '/api/public/cron/fetch-daily-trends'
      preLoaderRoute: typeof ApiPublicCronFetchDailyTrendsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/cron/deadline-reminders': {
      id: '/api/public/cron/deadline-reminders'
      path: '/api/public/cron/deadline-reminders'
      fullPath: '/api/public/cron/deadline-reminders'
      preLoaderRoute: typeof ApiPublicCronDeadlineRemindersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/escrow/release': {
      id: '/api/payments/escrow/release'
      path: '/api/payments/escrow/release'
      fullPath: '/api/payments/escrow/release'
      preLoaderRoute: typeof ApiPaymentsEscrowReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/connect/onboard': {
      id: '/api/payments/connect/onboard'
      path: '/api/payments/connect/onboard'
      fullPath: '/api/payments/connect/onboard'
      preLoaderRoute: typeof ApiPaymentsConnectOnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/payments/cashout/process': {
      id: '/api/payments/cashout/process'
      path: '/api/payments/cashout/process'
      fullPath: '/api/payments/cashout/process'
      preLoaderRoute: typeof ApiPaymentsCashoutProcessRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthRouteChildren {
  AuthCallbackRoute: typeof AuthCallbackRoute
  AuthForgotRoute: typeof AuthForgotRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthCallbackRoute: AuthCallbackRoute,
  AuthForgotRoute: AuthForgotRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

interface HelpRouteChildren {
  HelpBrandingRoute: typeof HelpBrandingRoute
  HelpBriefRoute: typeof HelpBriefRoute
  HelpGettingStartedRoute: typeof HelpGettingStartedRoute
  HelpLineRoute: typeof HelpLineRoute
  HelpPaymentsRoute: typeof HelpPaymentsRoute
  HelpPlansRoute: typeof HelpPlansRoute
  HelpQuotationsRoute: typeof HelpQuotationsRoute
  HelpTaxRoute: typeof HelpTaxRoute
}

const HelpRouteChildren: HelpRouteChildren = {
  HelpBrandingRoute: HelpBrandingRoute,
  HelpBriefRoute: HelpBriefRoute,
  HelpGettingStartedRoute: HelpGettingStartedRoute,
  HelpLineRoute: HelpLineRoute,
  HelpPaymentsRoute: HelpPaymentsRoute,
  HelpPlansRoute: HelpPlansRoute,
  HelpQuotationsRoute: HelpQuotationsRoute,
  HelpTaxRoute: HelpTaxRoute,
}

const HelpRouteWithChildren = HelpRoute._addFileChildren(HelpRouteChildren)

interface InhouseOrgSlugWorkspaceSlugRouteChildren {
  InhouseOrgSlugWorkspaceSlugCanvasRoute: typeof InhouseOrgSlugWorkspaceSlugCanvasRoute
  InhouseOrgSlugWorkspaceSlugChatRoute: typeof InhouseOrgSlugWorkspaceSlugChatRoute
  InhouseOrgSlugWorkspaceSlugKanbanRoute: typeof InhouseOrgSlugWorkspaceSlugKanbanRoute
  InhouseOrgSlugWorkspaceSlugMonitorRoute: typeof InhouseOrgSlugWorkspaceSlugMonitorRoute
  InhouseOrgSlugWorkspaceSlugTodosRoute: typeof InhouseOrgSlugWorkspaceSlugTodosRoute
}

const InhouseOrgSlugWorkspaceSlugRouteChildren: InhouseOrgSlugWorkspaceSlugRouteChildren =
  {
    InhouseOrgSlugWorkspaceSlugCanvasRoute:
      InhouseOrgSlugWorkspaceSlugCanvasRoute,
    InhouseOrgSlugWorkspaceSlugChatRoute: InhouseOrgSlugWorkspaceSlugChatRoute,
    InhouseOrgSlugWorkspaceSlugKanbanRoute:
      InhouseOrgSlugWorkspaceSlugKanbanRoute,
    InhouseOrgSlugWorkspaceSlugMonitorRoute:
      InhouseOrgSlugWorkspaceSlugMonitorRoute,
    InhouseOrgSlugWorkspaceSlugTodosRoute:
      InhouseOrgSlugWorkspaceSlugTodosRoute,
  }

const InhouseOrgSlugWorkspaceSlugRouteWithChildren =
  InhouseOrgSlugWorkspaceSlugRoute._addFileChildren(
    InhouseOrgSlugWorkspaceSlugRouteChildren,
  )

interface InhouseOrgSlugRouteChildren {
  InhouseOrgSlugWorkspaceSlugRoute: typeof InhouseOrgSlugWorkspaceSlugRouteWithChildren
  InhouseOrgSlugSettingsRoute: typeof InhouseOrgSlugSettingsRoute
}

const InhouseOrgSlugRouteChildren: InhouseOrgSlugRouteChildren = {
  InhouseOrgSlugWorkspaceSlugRoute:
    InhouseOrgSlugWorkspaceSlugRouteWithChildren,
  InhouseOrgSlugSettingsRoute: InhouseOrgSlugSettingsRoute,
}

const InhouseOrgSlugRouteWithChildren = InhouseOrgSlugRoute._addFileChildren(
  InhouseOrgSlugRouteChildren,
)

interface InhouseRouteChildren {
  InhouseOrgSlugRoute: typeof InhouseOrgSlugRouteWithChildren
  InhouseInviteTokenRoute: typeof InhouseInviteTokenRoute
}

const InhouseRouteChildren: InhouseRouteChildren = {
  InhouseOrgSlugRoute: InhouseOrgSlugRouteWithChildren,
  InhouseInviteTokenRoute: InhouseInviteTokenRoute,
}

const InhouseRouteWithChildren =
  InhouseRoute._addFileChildren(InhouseRouteChildren)

interface TrackTokenRouteChildren {
  TrackTokenCheckoutRoute: typeof TrackTokenCheckoutRoute
}

const TrackTokenRouteChildren: TrackTokenRouteChildren = {
  TrackTokenCheckoutRoute: TrackTokenCheckoutRoute,
}

const TrackTokenRouteWithChildren = TrackTokenRoute._addFileChildren(
  TrackTokenRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRouteWithChildren,
  CookiesRoute: CookiesRoute,
  CreativePartnerRoute: CreativePartnerRoute,
  DashboardRoute: DashboardRoute,
  HelpRoute: HelpRouteWithChildren,
  InhouseRoute: InhouseRouteWithChildren,
  LabsRoute: LabsRoute,
  LineLinkRoute: LineLinkRoute,
  LlmsDottxtRoute: LlmsDottxtRoute,
  MaintenanceRoute: MaintenanceRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  RefundRoute: RefundRoute,
  ResearchRoute: ResearchRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SurveyRoute: SurveyRoute,
  TermsRoute: TermsRoute,
  UnsubscribeRoute: UnsubscribeRoute,
  BlogSlugRoute: BlogSlugRoute,
  BriefTokenRoute: BriefTokenRoute,
  DevStripeConnectUiRoute: DevStripeConnectUiRoute,
  EmailUnsubscribeRoute: EmailUnsubscribeRoute,
  LicenseTokenRoute: LicenseTokenRoute,
  PSlugRoute: PSlugRoute,
  PayTokenRoute: PayTokenRoute,
  PlannerTokenRoute: PlannerTokenRoute,
  SignTokenRoute: SignTokenRoute,
  SupplierTokenRoute: SupplierTokenRoute,
  TrackTokenRoute: TrackTokenRouteWithChildren,
  VisionTokenRoute: VisionTokenRoute,
  BlogIndexRoute: BlogIndexRoute,
  ApiAssistantStreamRoute: ApiAssistantStreamRoute,
  ApiPaymentsCheckoutRoute: ApiPaymentsCheckoutRoute,
  ApiPublicCspReportRoute: ApiPublicCspReportRoute,
  LovableEmailSuppressionRoute: LovableEmailSuppressionRoute,
  ApiPaymentsCashoutProcessRoute: ApiPaymentsCashoutProcessRoute,
  ApiPaymentsConnectOnboardRoute: ApiPaymentsConnectOnboardRoute,
  ApiPaymentsEscrowReleaseRoute: ApiPaymentsEscrowReleaseRoute,
  ApiPublicCronDeadlineRemindersRoute: ApiPublicCronDeadlineRemindersRoute,
  ApiPublicCronFetchDailyTrendsRoute: ApiPublicCronFetchDailyTrendsRoute,
  ApiPublicCronMeetingCaptureCleanupRoute:
    ApiPublicCronMeetingCaptureCleanupRoute,
  ApiPublicCronPaymentRemindersRoute: ApiPublicCronPaymentRemindersRoute,
  ApiPublicPaymentsClientCheckoutRoute: ApiPublicPaymentsClientCheckoutRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  LovableEmailAuthPreviewRoute: LovableEmailAuthPreviewRoute,
  LovableEmailAuthWebhookRoute: LovableEmailAuthWebhookRoute,
  LovableEmailQueueProcessRoute: LovableEmailQueueProcessRoute,
  LovableEmailTransactionalPreviewRoute: LovableEmailTransactionalPreviewRoute,
  LovableEmailTransactionalSendRoute: LovableEmailTransactionalSendRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
